import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { getPprDatasetSummary, formatPprCurrency, formatPprDate } from "@/lib/ppr"
import { getCountiesComparedRows, getNationalActivitySnapshot, getNationalOverviewSnapshot, signedPercent } from "@/lib/ppr-analytics"
import { formatPlanningDate } from "@/lib/planning"
import { planningDecisionTone, planningStateBadgeClasses } from "@/lib/planning-state-presentation"
import { PLANNING_PUBLIC_CATEGORIES, getPlanningPublicCategorySummaries } from "@/lib/planning-public-categories"
import { getHomepageCountyPlanningStats, getHomepageNotablePlanning, getHomepagePlanningSummary, type HomepageNotablePlanningItem } from "@/lib/homepage-data"

export const metadata: Metadata = { title: "Property Research Ireland: Planning & Sold Prices | OpenList", description: "Research any property or area in Ireland. See recorded sale prices, significant planning activity, recent decisions and how an area is changing.", alternates: { canonical: "/" } }
export const revalidate = 21600

const places = [["dublin","Co. Dublin"],["cork","Co. Cork"],["galway","Co. Galway"],["limerick","Co. Limerick"],["waterford","Co. Waterford"],["kildare","Co. Kildare"],["wicklow","Co. Wicklow"],["meath","Co. Meath"]] as const
const categoryLabels: Record<string,string> = {"residential-large":"Large residential",energy:"Energy & renewables",infrastructure:"Infrastructure","data-centre":"Data centres",transport:"Transport",retail:"Retail",hospitality:"Hotels & restaurants",industrial:"Industrial & logistics",waste:"Waste & recycling",quarry:"Quarrying","student-accommodation":"Student accommodation",commercial:"Commercial"}
function categoryLabel(item: HomepageNotablePlanningItem){return item.categories.map(c=>categoryLabels[c]).find(Boolean)??"Significant development"}
function itemTitle(item: HomepageNotablePlanningItem){return item.displayName||item.location||item.proposal||`Planning ${item.reference}`}
function shortText(value:string|null,max=165){if(!value)return null;const text=value.replace(/\s+/g," ").trim();return text.length>max?`${text.slice(0,max-1).trimEnd()}…`:text}
function isDecision(item:HomepageNotablePlanningItem){const text=`${item.status??""} ${item.decisionText??""}`.toLowerCase();return Boolean(item.decisionDate)||/grant|permission|refus|withdraw|invalid|appeal|conditional/.test(text)}
function diverseNotables(items:HomepageNotablePlanningItem[],limit:number){const selected:HomepageNotablePlanningItem[]=[];const seen=new Set<string>();for(const item of items){const c=categoryLabel(item);if(!seen.has(c)){selected.push(item);seen.add(c)}if(selected.length===limit)return selected}for(const item of items){if(!selected.some(x=>x.applicationId===item.applicationId))selected.push(item);if(selected.length===limit)break}return selected}
function metricTone(value:number|undefined){return value===undefined?"text-stone-950":value>0?"text-emerald-700":value<0?"text-rose-700":"text-stone-950"}
function NotableStatusBadge({item,preferDecision=false}:{item:HomepageNotablePlanningItem;preferDecision?:boolean}){const label=(preferDecision?item.decisionText?.trim():null)||item.status?.trim()||item.decisionText?.trim();if(!label)return null;return <span className={`inline-flex rounded-full border px-2.5 py-0.5 text-xs font-semibold ${planningStateBadgeClasses(planningDecisionTone(label))}`}>{label}</span>}

export default async function HomePage(){
 const [datasetSummary,planningSummary,notableItems,categorySummaries,nationalSnapshot,monthlyActivity,countyRows,countyPlanningStats]=await Promise.all([getPprDatasetSummary(),getHomepagePlanningSummary().catch(()=>({totalCount:0,latestRegistrationDate:null})),getHomepageNotablePlanning().catch(()=>[]),getPlanningPublicCategorySummaries().catch(()=>[]),getNationalOverviewSnapshot("last-year"),getNationalActivitySnapshot(),getCountiesComparedRows().catch(()=>[]),getHomepageCountyPlanningStats().catch(()=>[])])
 const nf=new Intl.NumberFormat("en-IE");const activeNotables=notableItems.filter(item=>!isDecision(item));const live=diverseNotables(activeNotables,6);const decisions=notableItems.filter(isDecision).sort((a,b)=>String(b.decisionDate||"").localeCompare(String(a.decisionDate||""))).slice(0,4)
 const cats=PLANNING_PUBLIC_CATEGORIES.filter(c=>["large-residential","wind-farms","solar-energy","data-centres","retail","hotels-restaurants","infrastructure"].includes(c.slug)).map(c=>({...c,count:categorySummaries.find(s=>s.slug===c.slug)?.count??0})).filter(c=>c.count>=3)
 const countyBySlug=new Map(countyRows.map(row=>[row.slug,row]));const countyPlanningBySlug=new Map(countyPlanningStats.map(row=>[row.slug,row.openCount]))
 return <main className="min-h-screen bg-stone-50 text-stone-900">
  <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16 lg:py-20"><div className="grid gap-10 lg:grid-cols-[1.12fr_.88fr] lg:items-center lg:gap-12"><div className="max-w-[700px]"><p className="text-sm uppercase tracking-[.25em] text-stone-500">PROPERTY RESEARCH FOR IRELAND</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl md:text-[3.5rem] md:leading-[1.05]">Research any property or area in Ireland</h1><p className="mt-5 max-w-[39rem] text-base leading-7 text-stone-600 sm:text-lg sm:leading-8">See what sold nearby, what is proposed, the significant developments changing an area and the latest planning decisions.</p><form action="/search" className="mt-7 flex max-w-2xl gap-2 rounded-2xl border border-stone-300 bg-white p-2 shadow-sm"><input type="search" name="q" aria-label="Search OpenList" placeholder="Search an address, area, Eircode or planning reference" className="min-h-12 min-w-0 flex-1 rounded-xl px-3 text-sm outline-none placeholder:text-stone-400 focus:bg-stone-50 sm:text-base"/><button className="min-h-12 rounded-xl bg-stone-950 px-5 text-sm font-semibold text-white hover:bg-stone-700">Search</button></form><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm font-medium text-stone-600"><Link href="/planning">Browse Planning →</Link><Link href="/sold-prices">Browse Sold Prices →</Link></div><div className="mt-7 flex flex-wrap gap-x-3 gap-y-1.5 border-y border-stone-200 py-4 text-sm text-stone-600">{planningSummary.totalCount>0&&<span><strong className="text-stone-900">{nf.format(planningSummary.totalCount)}</strong> planning applications</span>}<span>·</span><span><strong className="text-stone-900">{nf.format(datasetSummary.salesCount)}</strong> recorded sales</span>{datasetSummary.latestSaleDate&&<><span>·</span><span>Sold prices through <strong className="text-stone-900">{formatPprDate(datasetSummary.latestSaleDate)}</strong></span></>}</div></div><div className="relative h-[270px] overflow-hidden rounded-[32px] bg-white shadow-sm sm:h-[360px] lg:h-[430px]"><Image src="/home-planning-aerial-v2.jpg" alt="Irish neighbourhood and active development" fill priority sizes="(max-width:1024px) 100vw,45vw" className="object-cover"/></div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-emerald-700">Live planning intelligence</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Significant developments to watch</h2><p className="mt-3 max-w-2xl text-stone-600">Notable applications still moving through the planning process, selected across development types and locations rather than routine household applications.</p></div><Link href="/planning/categories" className="text-sm font-semibold text-stone-700">Explore all categories →</Link></div>{cats.length>0&&<div className="mt-6 flex flex-wrap gap-2">{cats.map(c=><Link key={c.slug} href={`/planning/categories/${c.slug}`} className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-sm font-medium text-emerald-900">{c.shortLabel}<span className="ml-1.5 text-emerald-600">{c.count}</span></Link>)}</div>}{live.length>0?<div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{live.map(item=><Link key={item.applicationId} href={`/search?q=${encodeURIComponent(item.reference)}`} className="group flex min-h-52 flex-col rounded-3xl border border-stone-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex flex-wrap items-start justify-between gap-2"><span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-semibold">{categoryLabel(item)}</span><NotableStatusBadge item={item}/></div><h3 className="mt-4 text-lg font-semibold tracking-tight group-hover:text-emerald-800">{shortText(itemTitle(item),90)}</h3>{item.displayName&&item.location&&<p className="mt-1 text-sm text-stone-500">{shortText(item.location,80)}</p>}<p className="mt-3 line-clamp-3 text-sm leading-6 text-stone-600">{shortText(item.proposal,180)||`Planning reference ${item.reference}`}</p><p className="mt-auto pt-4 text-xs font-medium text-stone-500">{item.registrationDate?`Registered ${formatPlanningDate(item.registrationDate)}`:item.reference} · View application →</p></Link>)}</div>:<div className="mt-7 rounded-3xl border border-stone-200 bg-white p-6 text-stone-600">No significant pre-decision applications are available in the current selection.</div>}</section>
  {decisions.length>0&&<section className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="rounded-[32px] border border-stone-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-stone-500">Recent notable decisions</p><h2 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Important applications recently decided</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-500">Notable applications that have reached a planning decision, kept separate from the active applications above.</p><div className="mt-6 divide-y divide-stone-200">{decisions.map(item=><Link key={item.applicationId} href={`/search?q=${encodeURIComponent(item.reference)}`} className="grid gap-2 py-4 first:pt-0 last:pb-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">{categoryLabel(item)}</span><NotableStatusBadge item={item} preferDecision/></div><h3 className="mt-1 font-semibold">{shortText(itemTitle(item),110)}</h3>{item.displayName&&item.location?<p className="mt-1 text-sm text-stone-500">{shortText(item.location,100)}</p>:null}</div><span className="text-sm font-medium text-stone-600">{item.decisionDate?formatPlanningDate(item.decisionDate):"View"} →</span></Link>)}</div></div></section>}
  <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.2em] text-stone-500">Ireland property market</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Market snapshot</h2><p className="mt-2 text-sm text-stone-500">Last 12 months</p></div><Link href="/sold-prices" className="text-sm font-semibold text-stone-700">Explore Sold Prices →</Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">Median sale price</p><p className="mt-2 text-2xl font-semibold tracking-tight text-stone-950">{formatPprCurrency(nationalSnapshot.medianPrice)}</p><p className="mt-2 text-sm leading-6 text-stone-500">{nationalSnapshot.p25!==undefined&&nationalSnapshot.p75!==undefined?`Middle 50%: ${formatPprCurrency(nationalSnapshot.p25)} to ${formatPprCurrency(nationalSnapshot.p75)}`:"Recent recorded sales"}</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">Year-on-year price change</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${metricTone(nationalSnapshot.yoyChangePct)}`}>{nationalSnapshot.yoyChangePct!==undefined?signedPercent(nationalSnapshot.yoyChangePct):"Limited data"}</p><p className="mt-2 text-sm leading-6 text-stone-500">Median sale price vs previous 12 months</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-sm text-stone-500">Sales activity</p><p className={`mt-2 text-2xl font-semibold tracking-tight ${metricTone(monthlyActivity.yoyChangePct)}`}>{monthlyActivity.yoyChangePct!==undefined?signedPercent(monthlyActivity.yoyChangePct):"Limited data"}</p><p className="mt-2 text-sm leading-6 text-stone-500">{monthlyActivity.currentPeriodLabel} vs {monthlyActivity.previousPeriodLabel}</p></div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="rounded-[32px] border border-stone-200 bg-white p-7 shadow-sm sm:p-9"><p className="text-sm font-semibold uppercase tracking-[.18em] text-stone-500">Explore counties</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Start with a county</h2><p className="mt-3 max-w-2xl text-stone-600">Compare sold-price movement and planning activity, then jump into the underlying records.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{places.map(([slug,label])=>{const county=countyBySlug.get(slug);const planningCount=countyPlanningBySlug.get(slug);return <div key={slug} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><h3 className="font-semibold">{label}</h3><p className="mt-4 text-[11px] font-semibold uppercase tracking-[.14em] text-stone-500">Sold prices · 1 yr</p><div className="mt-2 grid grid-cols-2 gap-3 border-b border-stone-200 pb-3"><div><p className="text-xs text-stone-500">Price trend</p><p className={`mt-1 text-lg font-semibold ${metricTone(county?.yoyChangePct)}`}>{county?.yoyChangePct!==undefined?signedPercent(county.yoyChangePct):"Limited"}</p></div><div><p className="text-xs text-stone-500">Sales activity</p><p className={`mt-1 text-lg font-semibold ${metricTone(county?.activityChangePct)}`}>{county?.activityChangePct!==undefined?signedPercent(county.activityChangePct):"Limited"}</p></div></div>{planningCount!==undefined?<div className="mt-3"><span className="inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-900">Planning · {nf.format(planningCount)} pre-decision</span></div>:null}<div className="mt-3 flex gap-3 text-sm"><Link href={`/planning/${slug}`} className="font-medium text-stone-700">Planning →</Link><Link href={`/sold-prices/${slug}`} className="font-medium text-stone-700">Sold prices →</Link></div></div>})}</div></div></section>
  <section className="mx-auto max-w-6xl px-4 pb-16 sm:px-6"><div className="border-t border-stone-200 pt-6 text-sm leading-6 text-stone-500"><strong className="font-semibold text-stone-700">Source & limitations.</strong> OpenList organises public planning and Property Price Register information for research. Planning records should be checked against the relevant authority for formal or legal purposes, and sold-price data is not a property valuation.</div></section>
 </main>
}
