export type EircodeRoutingMarket = {
  county: string
  locality: string
  areaSlug: string
  label: string
}

type RoutingMarketTuple = readonly [
  county: string,
  label: string,
  areaSlug: string,
  locality?: string,
]

// Public routing-key areas current at August 2026. Routing keys identify broad
// postal delivery areas, not individual properties. Eight keys span multiple
// named markets; those are returned as choices and must not be collapsed to an
// arbitrary primary town. Every county + areaSlug pair below is verified in
// OpenList's ppr_area_stats market summaries.
const EIRCODE_ROUTING_MARKETS: Record<string, readonly RoutingMarketTuple[]> = {
  A41: [["Dublin", "Ballyboughal", "ballyboughal"]],
  A42: [["Dublin", "Garristown", "garristown"]],
  A45: [["Dublin", "Oldtown", "oldtown"]],
  A63: [["Wicklow", "Delgany", "delgany"], ["Wicklow", "Greystones", "greystones"], ["Wicklow", "Kilcoole", "kilcoole"], ["Wicklow", "Newcastle", "newcastle"], ["Wicklow", "Newtownmountkennedy", "newtownmountkennedy"]],
  A67: [["Wicklow", "Rathnew", "rathnew"], ["Wicklow", "Wicklow", "wicklow"]],
  A75: [["Monaghan", "Ballybay", "ballybay"], ["Monaghan", "Castleblayney", "castleblayney"]],
  A81: [["Monaghan", "Carrickmacross", "carrickmacross"]],
  A82: [["Meath", "Kells", "kells"], ["Cavan", "Kingscourt", "kingscourt"], ["Cavan", "Virginia", "virginia"]],
  A83: [["Meath", "Enfield", "enfield"], ["Meath", "Summerhill", "summerhill"]],
  A84: [["Meath", "Ashbourne", "ashbourne"]],
  A85: [["Meath", "Dunshaughlin", "dunshaughlin"], ["Meath", "Ratoath", "ratoath"]],
  A86: [["Meath", "Dunboyne", "dunboyne"]],
  A91: [["Louth", "Dundalk", "dundalk"]],
  A92: [["Louth", "Ardee", "ardee"], ["Louth", "Drogheda", "drogheda"], ["Meath", "Laytown-Bettystown-Mornington", "bettystown", "Bettystown"]],
  A94: [["Dublin", "Blackrock", "blackrock"], ["Dublin", "Booterstown", "booterstown"], ["Dublin", "Monkstown", "monkstown"]],
  A96: [["Dublin", "Glenageary", "glenageary"]],
  A98: [["Wicklow", "Bray", "bray"]],
  C15: [["Meath", "Navan", "navan"]],
  D01: [["Dublin", "Dublin 1", "dublin-1"]],
  D02: [["Dublin", "Dublin 2", "dublin-2"]],
  D03: [["Dublin", "Dublin 3", "dublin-3"]],
  D04: [["Dublin", "Dublin 4", "dublin-4"]],
  D05: [["Dublin", "Dublin 5", "dublin-5"]],
  D06: [["Dublin", "Dublin 6", "dublin-6"]],
  D07: [["Dublin", "Dublin 7", "dublin-7"]],
  D08: [["Dublin", "Dublin 8", "dublin-8"]],
  D09: [["Dublin", "Dublin 9", "dublin-9"]],
  D10: [["Dublin", "Dublin 10", "dublin-10"]],
  D11: [["Dublin", "Dublin 11", "dublin-11"]],
  D12: [["Dublin", "Dublin 12", "dublin-12"]],
  D13: [["Dublin", "Dublin 13", "dublin-13"]],
  D14: [["Dublin", "Dublin 14", "dublin-14"]],
  D15: [["Dublin", "Dublin 15", "dublin-15"]],
  D16: [["Dublin", "Dublin 16", "dublin-16"]],
  D17: [["Dublin", "Dublin 17", "dublin-17"]],
  D18: [["Dublin", "Dublin 18", "dublin-18"]],
  D20: [["Dublin", "Dublin 20", "dublin-20"]],
  D22: [["Dublin", "Dublin 22", "dublin-22"]],
  D24: [["Dublin", "Dublin 24", "dublin-24"]],
  D6W: [["Dublin", "Dublin 6W", "dublin-6w"]],
  E21: [["Tipperary", "Cahir", "cahir"]],
  E25: [["Tipperary", "Cashel", "cashel"]],
  E32: [["Tipperary", "Carrick-on-Suir", "carrick-on-suir"]],
  E34: [["Tipperary", "Tipperary", "tipperary"]],
  E41: [["Tipperary", "Thurles", "thurles"]],
  E45: [["Tipperary", "Nenagh", "nenagh"]],
  E53: [["Tipperary", "Roscrea", "roscrea"]],
  E91: [["Tipperary", "Clonmel", "clonmel"]],
  F12: [["Mayo", "Claremorris", "claremorris"]],
  F23: [["Mayo", "Castlebar", "castlebar"]],
  F26: [["Mayo", "Ballina", "ballina"]],
  F28: [["Mayo", "Westport", "westport"]],
  F31: [["Mayo", "Ballinrobe", "ballinrobe"]],
  F35: [["Mayo", "Ballyhaunis", "ballyhaunis"]],
  F42: [["Roscommon", "Roscommon", "roscommon"]],
  F45: [["Roscommon", "Castlerea", "castlerea"]],
  F52: [["Roscommon", "Boyle", "boyle"]],
  F56: [["Sligo", "Ballymote", "ballymote"]],
  F91: [["Sligo", "Sligo", "sligo"]],
  F92: [["Donegal", "Letterkenny", "letterkenny"]],
  F93: [["Donegal", "Lifford", "lifford"]],
  F94: [["Donegal", "Donegal", "donegal"]],
  H12: [["Cavan", "Cavan", "cavan"]],
  H14: [["Cavan", "Belturbet", "belturbet"]],
  H16: [["Cavan", "Cootehill", "cootehill"]],
  H18: [["Monaghan", "Monaghan", "monaghan"]],
  H23: [["Monaghan", "Clones", "clones"]],
  H53: [["Galway", "Ballinasloe", "ballinasloe"]],
  H54: [["Galway", "Tuam", "tuam"]],
  H62: [["Galway", "Loughrea", "loughrea"]],
  H65: [["Galway", "Athenry", "athenry"]],
  H71: [["Galway", "Clifden", "clifden"]],
  H91: [["Galway", "Galway", "galway"]],
  K32: [["Dublin", "Balbriggan", "balbriggan"]],
  K34: [["Dublin", "Skerries", "skerries"]],
  K36: [["Dublin", "Malahide", "malahide"]],
  K45: [["Dublin", "Lusk", "lusk"]],
  K56: [["Dublin", "Rush", "rush"]],
  K67: [["Dublin", "Swords and Dublin Airport", "swords", "Swords"]],
  K78: [["Dublin", "Lucan", "lucan"]],
  N37: [["Westmeath", "Athlone", "athlone"]],
  N39: [["Longford", "Longford", "longford"]],
  N41: [["Leitrim", "Carrick-on-Shannon", "carrick-on-shannon"]],
  N91: [["Westmeath", "Mullingar", "mullingar"]],
  P12: [["Cork", "Macroom", "macroom"]],
  P14: [["Cork", "Crookstown", "crookstown"]],
  P17: [["Cork", "Kinsale", "kinsale"]],
  P24: [["Cork", "Cobh", "cobh"]],
  P25: [["Cork", "Midleton", "midleton"]],
  P31: [["Cork", "Ballincollig", "ballincollig"]],
  P32: [["Cork", "Donoughmore", "donoughmore"]],
  P36: [["Cork", "Youghal", "youghal"]],
  P43: [["Cork", "Carrigaline", "carrigaline"]],
  P47: [["Cork", "Dunmanway", "dunmanway"]],
  P51: [["Cork", "Mallow", "mallow"]],
  P56: [["Cork", "Charleville", "charleville"]],
  P61: [["Cork", "Fermoy", "fermoy"]],
  P67: [["Cork", "Mitchelstown", "mitchelstown"]],
  P72: [["Cork", "Bandon", "bandon"]],
  P75: [["Cork", "Bantry", "bantry"]],
  P81: [["Cork", "Skibbereen", "skibbereen"]],
  P85: [["Cork", "Clonakilty", "clonakilty"]],
  R14: [["Kildare", "Athy", "athy"]],
  R21: [["Carlow", "Muine Bheag", "muine-bheag"]],
  R32: [["Laois", "Portlaoise", "portlaoise"]],
  R35: [["Offaly", "Tullamore", "tullamore"]],
  R42: [["Offaly", "Birr", "birr"]],
  R45: [["Offaly", "Edenderry", "edenderry"]],
  R51: [["Kildare", "Kildare", "kildare"]],
  R56: [["Kildare", "Curragh Camp", "curragh-camp"]],
  R93: [["Carlow", "Carlow", "carlow"]],
  R95: [["Kilkenny", "Kilkenny", "kilkenny"]],
  T12: [["Cork", "Cork (centre and southside)", "cork", "Cork"]],
  T23: [["Cork", "Cork (northside)", "cork", "Cork"]],
  T34: [["Cork", "Whitechurch", "whitechurch"]],
  T45: [["Cork", "Little Island", "little-island"]],
  T56: [["Cork", "Watergrasshill", "watergrasshill"]],
  V14: [["Clare", "Shannon", "shannon"]],
  V15: [["Clare", "Kilrush", "kilrush"]],
  V23: [["Kerry", "Caherciveen", "caherciveen"]],
  V31: [["Kerry", "Listowel", "listowel"]],
  V35: [["Limerick", "Kilmallock", "kilmallock"]],
  V42: [["Limerick", "Newcastle West", "newcastle-west"]],
  V92: [["Kerry", "Tralee", "tralee"]],
  V93: [["Kerry", "Killarney", "killarney"]],
  V94: [["Limerick", "Limerick", "limerick"]],
  V95: [["Clare", "Ennis", "ennis"]],
  W12: [["Kildare", "Newbridge", "newbridge"]],
  W23: [["Kildare", "Maynooth", "maynooth"]],
  W34: [["Kildare", "Monasterevin", "monasterevin"]],
  W91: [["Kildare", "Naas", "naas"]],
  X35: [["Waterford", "Dungarvan", "dungarvan"]],
  X42: [["Waterford", "Kilmacthomas", "kilmacthomas"]],
  X91: [["Waterford", "Waterford", "waterford"]],
  Y14: [["Wicklow", "Arklow", "arklow"]],
  Y21: [["Wexford", "Enniscorthy", "enniscorthy"]],
  Y25: [["Wexford", "Gorey", "gorey"]],
  Y34: [["Wexford", "New Ross", "new-ross"]],
  Y35: [["Wexford", "Wexford", "wexford"]],
}

export const EIRCODE_ROUTING_KEY_COUNT = Object.keys(EIRCODE_ROUTING_MARKETS).length
export const EIRCODE_ROUTING_MARKET_COUNT = Object.values(
  EIRCODE_ROUTING_MARKETS
).reduce((total, markets) => total + markets.length, 0)
export const EIRCODE_MULTI_MARKET_KEY_COUNT = Object.values(
  EIRCODE_ROUTING_MARKETS
).filter((markets) => markets.length > 1).length

export function getEircodeRoutingMarkets(routingKey: string) {
  return (EIRCODE_ROUTING_MARKETS[routingKey.trim().toUpperCase()] ?? []).map(
    ([county, label, areaSlug, locality = label]) => ({
      county,
      locality,
      areaSlug,
      label,
    })
  )
}
