export const BASE_PPR_MARKETS = [
  { name: "Dublin", slug: "dublin", marketType: "county" },
  { name: "Cork", slug: "cork", marketType: "county" },
  { name: "Galway", slug: "galway", marketType: "county" },
  { name: "Limerick", slug: "limerick", marketType: "county" },
  { name: "Kildare", slug: "kildare", marketType: "county" },
  { name: "Wexford", slug: "wexford", marketType: "county" },
  { name: "Waterford", slug: "waterford", marketType: "county" },
  { name: "Meath", slug: "meath", marketType: "county" },
  { name: "Donegal", slug: "donegal", marketType: "county" },
  { name: "Wicklow", slug: "wicklow", marketType: "county" },
  { name: "Tipperary", slug: "tipperary", marketType: "county" },
  { name: "Mayo", slug: "mayo", marketType: "county" },
  { name: "Kerry", slug: "kerry", marketType: "county" },
  { name: "Clare", slug: "clare", marketType: "county" },
  { name: "Kilkenny", slug: "kilkenny", marketType: "county" },
  { name: "Cavan", slug: "cavan", marketType: "county" },
  { name: "Louth", slug: "louth", marketType: "county" },
  { name: "Westmeath", slug: "westmeath", marketType: "county" },
  { name: "Sligo", slug: "sligo", marketType: "county" },
  { name: "Roscommon", slug: "roscommon", marketType: "county" },
  { name: "Carlow", slug: "carlow", marketType: "county" },
  { name: "Longford", slug: "longford", marketType: "county" },
  { name: "Offaly", slug: "offaly", marketType: "county" },
  { name: "Laois", slug: "laois", marketType: "county" },
  { name: "Monaghan", slug: "monaghan", marketType: "county" },
  { name: "Leitrim", slug: "leitrim", marketType: "county" },
  { name: "Dublin 1", slug: "dublin-1", marketType: "dublin_district" },
  { name: "Dublin 2", slug: "dublin-2", marketType: "dublin_district" },
  { name: "Dublin 3", slug: "dublin-3", marketType: "dublin_district" },
  { name: "Dublin 4", slug: "dublin-4", marketType: "dublin_district" },
  { name: "Dublin 5", slug: "dublin-5", marketType: "dublin_district" },
  { name: "Dublin 6", slug: "dublin-6", marketType: "dublin_district" },
  { name: "Dublin 6W", slug: "dublin-6w", marketType: "dublin_district" },
  { name: "Dublin 7", slug: "dublin-7", marketType: "dublin_district" },
  { name: "Dublin 8", slug: "dublin-8", marketType: "dublin_district" },
  { name: "Dublin 9", slug: "dublin-9", marketType: "dublin_district" },
  { name: "Dublin 10", slug: "dublin-10", marketType: "dublin_district" },
  { name: "Dublin 11", slug: "dublin-11", marketType: "dublin_district" },
  { name: "Dublin 12", slug: "dublin-12", marketType: "dublin_district" },
  { name: "Dublin 13", slug: "dublin-13", marketType: "dublin_district" },
  { name: "Dublin 14", slug: "dublin-14", marketType: "dublin_district" },
  { name: "Dublin 15", slug: "dublin-15", marketType: "dublin_district" },
  { name: "Dublin 16", slug: "dublin-16", marketType: "dublin_district" },
  { name: "Dublin 18", slug: "dublin-18", marketType: "dublin_district" },
  { name: "Dublin 22", slug: "dublin-22", marketType: "dublin_district" },
  { name: "Dublin 24", slug: "dublin-24", marketType: "dublin_district" },
  { name: "Drogheda", slug: "drogheda", marketType: "town_suburb" },
  { name: "Dundalk", slug: "dundalk", marketType: "town_suburb" },
  { name: "Navan", slug: "navan", marketType: "town_suburb" },
  { name: "Portlaoise", slug: "portlaoise", marketType: "town_suburb" },
  { name: "Lucan", slug: "lucan", marketType: "town_suburb" },
  { name: "Swords", slug: "swords", marketType: "town_suburb" },
  { name: "Naas", slug: "naas", marketType: "town_suburb" },
  { name: "Gorey", slug: "gorey", marketType: "town_suburb" },
  {
    name: "Blackrock",
    slug: "blackrock-dublin",
    marketType: "town_suburb",
    county: "Dublin",
    areaSlug: "blackrock",
    displayName: "Blackrock, Dublin",
  },
  { name: "Athlone", slug: "athlone", marketType: "town_suburb" },
  { name: "Tralee", slug: "tralee", marketType: "town_suburb" },
  { name: "Ennis", slug: "ennis", marketType: "town_suburb" },
  { name: "Mullingar", slug: "mullingar", marketType: "town_suburb" },
  { name: "Letterkenny", slug: "letterkenny", marketType: "town_suburb" },
  { name: "Enniscorthy", slug: "enniscorthy", marketType: "town_suburb" },
  { name: "Mallow", slug: "mallow", marketType: "town_suburb" },
  { name: "Bray", slug: "bray", marketType: "town_suburb" },
  { name: "Dun Laoghaire", slug: "dun-laoghaire", marketType: "town_suburb" },
  { name: "Killarney", slug: "killarney", marketType: "town_suburb" },
  { name: "Newbridge", slug: "newbridge", marketType: "town_suburb" },
  { name: "Midleton", slug: "midleton", marketType: "town_suburb" },
  { name: "Celbridge", slug: "celbridge", marketType: "town_suburb" },
  { name: "Maynooth", slug: "maynooth", marketType: "town_suburb" },
  { name: "Douglas", slug: "douglas", marketType: "town_suburb" },
  { name: "Malahide", slug: "malahide", marketType: "town_suburb" },
  { name: "Carrigaline", slug: "carrigaline", marketType: "town_suburb" },
  { name: "Greystones", slug: "greystones", marketType: "town_suburb" },
  { name: "Nenagh", slug: "nenagh", marketType: "town_suburb" },
  { name: "Castlebar", slug: "castlebar", marketType: "town_suburb" },
  { name: "Clonmel", slug: "clonmel", marketType: "town_suburb" },
  { name: "Ballina", slug: "ballina", marketType: "town_suburb" },
  { name: "Ballinasloe", slug: "ballinasloe", marketType: "town_suburb" },
  { name: "Balbriggan", slug: "balbriggan", marketType: "town_suburb" },
  { name: "Tullamore", slug: "tullamore", marketType: "town_suburb" },
  { name: "Thurles", slug: "thurles", marketType: "town_suburb" },
  { name: "Ashbourne", slug: "ashbourne", marketType: "town_suburb" },
  { name: "Leixlip", slug: "leixlip", marketType: "town_suburb" },
  { name: "Tuam", slug: "tuam", marketType: "town_suburb" },
  { name: "Dungarvan", slug: "dungarvan", marketType: "town_suburb" },
  { name: "Castletroy", slug: "castletroy", marketType: "town_suburb" },
  { name: "Cobh", slug: "cobh", marketType: "town_suburb" },
  { name: "Kilcock", slug: "kilcock", marketType: "town_suburb" },
  { name: "Tramore", slug: "tramore", marketType: "town_suburb" },
  { name: "Athy", slug: "athy", marketType: "town_suburb" },
  { name: "Glanmire", slug: "glanmire", marketType: "town_suburb" },
  { name: "Citywest", slug: "citywest", marketType: "town_suburb" },
  { name: "Dunshaughlin", slug: "dunshaughlin", marketType: "town_suburb" },
  { name: "Bandon", slug: "bandon", marketType: "town_suburb" },
  { name: "Westport", slug: "westport", marketType: "town_suburb" },
  { name: "Castleknock", slug: "castleknock", marketType: "town_suburb" },
  { name: "Delgany", slug: "delgany", marketType: "town_suburb" },
  { name: "New Ross", slug: "new-ross", marketType: "town_suburb" },
  { name: "Clane", slug: "clane", marketType: "town_suburb" },
  { name: "Tallaght", slug: "tallaght", marketType: "town_suburb" },
  { name: "Donabate", slug: "donabate", marketType: "town_suburb" },
  { name: "Bettystown", slug: "bettystown", marketType: "town_suburb" },
  { name: "Kinsale", slug: "kinsale", marketType: "town_suburb" },
  { name: "Ballincollig", slug: "ballincollig", marketType: "town_suburb" },
  { name: "Leopardstown", slug: "leopardstown", marketType: "town_suburb" },
]

export const SUPPLEMENTAL_PPR_MARKET_SLUGS = [
  "clondalkin", "rathfarnham", "clonsilla", "crumlin", "clontarf", "raheny",
  "drumcondra", "glasnevin", "terenure", "artane", "drimnagh", "ballyfermot",
  "finglas", "santry", "walkinstown", "dundrum", "adamstown", "ballsbridge",
  "blanchardstown", "templeogue", "arklow", "ranelagh", "oranmore", "rathmines",
  "cabra", "stillorgan", "sandymount", "edenderry", "youghal", "inchicore",
  "donnybrook", "churchtown", "loughrea", "johnstown", "trim", "skerries",
  "clonee", "knocklyon", "harolds-cross", "shannon", "kells", "portarlington",
  "sutton", "dooradoyle", "ratoath", "saggart", "newcastle-west", "rathgar",
  "carrickmacross", "shankill", "doughiska", "portmarnock", "whitehall",
  "palmerstown", "listowel", "athenry", "castlerea", "beaumont", "claremorris",
  "coolock", "ardee", "virginia", "foxrock", "phibsborough", "roscrea",
  "blessington", "carrick-on-shannon", "sandyford", "clonakilty", "killiney",
  "boyle", "finglas-west", "baldoyle", "stepaside", "rush", "tullow", "lusk",
  "sallins", "east-wall", "abbeyside", "salthill", "kilkee", "ballinteer",
  "cashel", "mountmellick", "birr", "belturbet", "cahir", "bundoran",
  "charleville", "ballyhaunis", "monkstown", "kilcullen", "hollystown",
  "bantry", "gort", "glenageary", "firhouse", "ringsend", "fermoy", "kimmage",
  "dalkey", "kenmare", "kilrush", "rathcoole", "ballinrobe", "killester",
  "castleblayney", "edgeworthstown", "mount-merrion", "monasterevin",
  "rathangan", "newcastle", "bishopstown", "ballymote", "stoneybatter",
  "macroom", "moate", "mulhuddart", "carrick-on-suir", "swinford", "donaghmede",
  "athboy", "ballyjamesduff", "goatstown", "knocknacarra", "fairview",
  "tyrrelstown", "ballycullen", "marino", "clonskeagh", "ballybofey",
  "buncrana", "kinnegad", "killorglin", "claregalway", "ballybane",
  "ballymahon", "ballyshannon", "raheen", "rathnew", "finglas-east",
  "donnycarney", "skibbereen", "howth", "kanturk", "bailieborough", "clonard",
  "ballyconnell", "dunboyne", "tubbercurry", "mitchelstown", "collooney",
  "ballymun", "cabinteely", "strokestown", "wilton", "rialto", "springfield",
  "annacotty", "castleconnell", "corbally", "dunmore-east", "ennis-rd",
  "ferrybank", "galway-city", "gracedieu", "limerick-city", "lismore", "roscam",
  "waterford-city",
]

export const PPR_MARKET_OVERRIDES = {
  adamstown: { county: "Dublin" },
  bandon: { county: "Cork" },
  ballsbridge: { county: "Dublin" },
  ballinteer: { county: "Dublin" },
  ballycullen: { county: "Dublin" },
  ballymun: { county: "Dublin" },
  ballincollig: { county: "Cork" },
  blanchardstown: { county: "Dublin" },
  bishopstown: { county: "Cork" },
  bray: { county: "Wicklow" },
  cabinteely: { county: "Dublin" },
  cabra: { county: "Dublin" },
  carrigaline: { county: "Cork" },
  cobh: { county: "Cork" },
  churchtown: { county: "Dublin" },
  clonskeagh: { county: "Dublin" },
  coolock: { county: "Dublin" },
  douglas: { county: "Cork" },
  donaghmede: { county: "Dublin" },
  donnybrook: { county: "Dublin" },
  donnycarney: { county: "Dublin" },
  doughiska: { county: "Galway" },
  glanmire: { county: "Cork" },
  fairview: { county: "Dublin" },
  firhouse: { county: "Dublin" },
  foxrock: { county: "Dublin" },
  glenageary: { county: "Dublin" },
  goatstown: { county: "Dublin" },
  "harolds-cross": { county: "Dublin" },
  hollystown: { county: "Dublin" },
  howth: { county: "Dublin" },
  inchicore: { county: "Dublin" },
  kinsale: { county: "Cork" },
  killester: { county: "Dublin" },
  killiney: { county: "Dublin" },
  kimmage: { county: "Dublin" },
  knocklyon: { county: "Dublin" },
  mallow: { county: "Cork" },
  marino: { county: "Dublin" },
  midleton: { county: "Cork" },
  "mount-merrion": { county: "Dublin" },
  mulhuddart: { county: "Dublin" },
  annacotty: { county: "Limerick" },
  athenry: { county: "Galway" },
  ballinasloe: { county: "Galway" },
  beaumont: {
    slug: "beaumont-dublin",
    county: "Dublin",
    areaSlug: "beaumont",
    displayName: "Beaumont, Dublin",
  },
  castleconnell: { county: "Limerick" },
  corbally: { county: "Limerick" },
  dooradoyle: { county: "Limerick" },
  "dunmore-east": { county: "Waterford" },
  "ennis-rd": { county: "Limerick" },
  ferrybank: { county: "Waterford" },
  "galway-city": { county: "Galway", areaSlug: "galway" },
  gracedieu: { county: "Waterford" },
  johnstown: {
    slug: "johnstown-meath",
    county: "Meath",
    areaSlug: "johnstown",
    displayName: "Johnstown, Meath",
  },
  knocknacarra: { county: "Galway" },
  "limerick-city": { county: "Limerick", areaSlug: "limerick" },
  lismore: { county: "Waterford" },
  loughrea: { county: "Galway" },
  monkstown: {
    slug: "monkstown-dublin",
    county: "Dublin",
    areaSlug: "monkstown",
    displayName: "Monkstown, Dublin",
  },
  "newcastle-west": { county: "Limerick" },
  newcastle: {
    slug: "newcastle-galway",
    county: "Galway",
    areaSlug: "newcastle",
    displayName: "Newcastle, Galway",
  },
  oranmore: { county: "Galway" },
  palmerstown: { county: "Dublin" },
  phibsborough: { county: "Dublin" },
  portmarnock: { county: "Dublin" },
  raheen: { county: "Limerick" },
  ranelagh: { county: "Dublin" },
  rathgar: { county: "Dublin" },
  rathmines: { county: "Dublin" },
  rialto: { county: "Dublin" },
  ringsend: { county: "Dublin" },
  roscam: { county: "Galway" },
  salthill: { county: "Galway" },
  sandyford: { county: "Dublin" },
  sandymount: { county: "Dublin" },
  shankill: { county: "Dublin" },
  springfield: {
    slug: "springfield-dublin",
    county: "Dublin",
    areaSlug: "springfield",
    displayName: "Springfield, Dublin",
  },
  stillorgan: { county: "Dublin" },
  stoneybatter: { county: "Dublin" },
  sutton: { county: "Dublin" },
  templeogue: { county: "Dublin" },
  tuam: { county: "Galway" },
  tyrrelstown: { county: "Dublin" },
  "waterford-city": { county: "Waterford", areaSlug: "waterford" },
  whitehall: { county: "Dublin" },
  wilton: { slug: "wilton-cork", county: "Cork", areaSlug: "wilton" },
}

export const FEATURED_PPR_MARKETS = [
  "dublin",
  "cork",
  "galway",
  "limerick",
  "drogheda",
  "dundalk",
  "swords",
  "bray",
]

export const COMMUTER_TOWN_MARKET_SLUGS = [
  "drogheda",
  "dundalk",
  "bray",
  "greystones",
  "naas",
  "newbridge",
  "navan",
  "maynooth",
  "leixlip",
  "celbridge",
  "sallins",
  "kilcock",
  "ashbourne",
  "ratoath",
  "dunboyne",
  "trim",
  "bettystown",
  "arklow",
  "mullingar",
  "portlaoise",
]

export const COMMUTER_TOWN_DISTANCE_KM = {
  drogheda: 55,
  dundalk: 84,
  bray: 21,
  greystones: 28,
  naas: 39,
  newbridge: 49,
  navan: 51,
  maynooth: 27,
  leixlip: 18,
  celbridge: 24,
  sallins: 34,
  kilcock: 40,
  ashbourne: 24,
  ratoath: 31,
  dunboyne: 18,
  trim: 52,
  bettystown: 45,
  arklow: 69,
  mullingar: 79,
  portlaoise: 94,
}

export const COMPARISON_PAGE_MARKET_SLUGS = {
  corkCompared: [
    "bishopstown",
    "wilton-cork",
    "douglas",
    "ballincollig",
    "carrigaline",
    "glanmire",
    "midleton",
    "cobh",
    "mallow",
    "bandon",
    "kinsale",
    "fermoy",
    "youghal",
    "clonakilty",
  ],
  commuterTowns: [...COMMUTER_TOWN_MARKET_SLUGS],
  limerickCompared: [
    "limerick-city",
    "castletroy",
    "dooradoyle",
    "raheen",
    "annacotty",
    "corbally",
    "castleconnell",
    "newcastle-west",
  ],
  galwayCompared: [
    "galway-city",
    "salthill",
    "knocknacarra",
    "roscam",
    "oranmore",
    "athenry",
    "tuam",
    "loughrea",
    "ballinasloe",
    "newcastle-galway",
    "doughiska",
  ],
  waterfordCompared: [
    "waterford-city",
    "tramore",
    "dungarvan",
    "abbeyside",
    "dunmore-east",
    "ferrybank",
    "gracedieu",
    "lismore",
  ],
}
