create table if not exists public.bcms_source_probes (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  source_url text not null,
  resource_id text not null,
  last_modified timestamptz,
  source_hash text,
  source_size bigint,
  record_count bigint,
  metadata jsonb not null default '{}'::jsonb,
  changed_since_previous boolean,
  error text
);

create index if not exists bcms_source_probes_checked_at_idx
  on public.bcms_source_probes (checked_at desc);

alter table public.bcms_source_probes enable row level security;

comment on table public.bcms_source_probes is 'Daily observations of the NBCO/BCMS canonical BuildingsCNsCCCs resource metadata, used to establish real publication cadence before enabling full continuous ingestion.';
