create table if not exists public.planning_canonical_places (
  slug text primary key,
  display_name text not null,
  place_type text not null check (place_type in ('postal_district','settlement','suburb','locality','other')),
  county text,
  source text not null,
  confidence smallint not null default 100 check (confidence between 0 and 100),
  aggregate_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.planning_canonical_place_memberships (
  place_slug text not null references public.planning_canonical_places(slug) on delete cascade,
  authority_code text not null,
  locality_slug text not null,
  locality_label text not null,
  source text not null,
  confidence smallint not null default 100 check (confidence between 0 and 100),
  created_at timestamptz not null default now(),
  primary key (place_slug, authority_code, locality_slug)
);

create table if not exists public.planning_canonical_place_aliases (
  id bigint generated by default as identity primary key,
  place_slug text not null references public.planning_canonical_places(slug) on delete cascade,
  alias text not null,
  alias_normalized text not null,
  authority_code text,
  source text not null,
  confidence smallint not null default 100 check (confidence between 0 and 100),
  created_at timestamptz not null default now(),
  unique (place_slug, alias_normalized, authority_code)
);

create index if not exists planning_canonical_place_memberships_authority_idx
  on public.planning_canonical_place_memberships(authority_code, locality_slug);
create index if not exists planning_canonical_place_aliases_norm_idx
  on public.planning_canonical_place_aliases(alias_normalized, authority_code);

alter table public.planning_canonical_places enable row level security;
alter table public.planning_canonical_place_memberships enable row level security;
alter table public.planning_canonical_place_aliases enable row level security;

revoke all on public.planning_canonical_places from anon, authenticated;
revoke all on public.planning_canonical_place_memberships from anon, authenticated;
revoke all on public.planning_canonical_place_aliases from anon, authenticated;
grant select, insert, update, delete on public.planning_canonical_places to service_role;
grant select, insert, update, delete on public.planning_canonical_place_memberships to service_role;
grant select, insert, update, delete on public.planning_canonical_place_aliases to service_role;
grant usage, select on sequence public.planning_canonical_place_aliases_id_seq to service_role;

insert into public.planning_canonical_places (slug, display_name, place_type, county, source, confidence)
select distinct m.locality_slug, m.locality_label, 'postal_district', 'Dublin', 'planning_locality_membership', 100
from public.locality_seo_memberships m
where m.surface = 'planning'
  and m.left_at is null
  and m.locality_label ~ '^Dublin [0-9]+W?$'
on conflict (slug) do update
set display_name = excluded.display_name,
    place_type = excluded.place_type,
    county = excluded.county,
    confidence = greatest(public.planning_canonical_places.confidence, excluded.confidence),
    updated_at = now();

insert into public.planning_canonical_place_memberships
  (place_slug, authority_code, locality_slug, locality_label, source, confidence)
select m.locality_slug, m.authority_code, m.locality_slug, m.locality_label, 'planning_locality_membership', 100
from public.locality_seo_memberships m
where m.surface = 'planning'
  and m.left_at is null
  and m.authority_code is not null
  and m.locality_label ~ '^Dublin [0-9]+W?$'
on conflict (place_slug, authority_code, locality_slug) do update
set locality_label = excluded.locality_label,
    source = excluded.source,
    confidence = greatest(public.planning_canonical_place_memberships.confidence, excluded.confidence);

insert into public.planning_canonical_place_aliases
  (place_slug, alias, alias_normalized, authority_code, source, confidence)
select distinct p.slug, p.display_name, lower(regexp_replace(trim(p.display_name), '\s+', ' ', 'g')), null, 'canonical_label', 100
from public.planning_canonical_places p
where p.place_type = 'postal_district'
on conflict do nothing;

-- Multiple source memberships are evidence for review, not sufficient proof that a
-- real-world place crosses authority boundaries. Aggregate pages require explicit
-- curated approval. Dublin 16 is the first validated pilot.
update public.planning_canonical_places
set aggregate_enabled = false
where place_type = 'postal_district';

update public.planning_canonical_places
set aggregate_enabled = true,
    source = 'curated_cross_authority_pilot',
    confidence = 100,
    updated_at = now()
where slug = 'dublin-16'
  and exists (
    select 1 from public.planning_canonical_place_memberships m
    where m.place_slug = 'dublin-16' and m.authority_code = 'DLR'
  )
  and exists (
    select 1 from public.planning_canonical_place_memberships m
    where m.place_slug = 'dublin-16' and m.authority_code = 'SOUTHDUBLIN'
  );
